### ISSUE TITLE
Enable `require 'rmagic'` for compatability with rmagick versions 2.13.4 and higher

### ISSUE THREAD

**Issue by wconrad** [Serabe/RMagick4J#19]
rmagick, starting with version 2.13.4, renamed its top-level require from:

    RMagick

to

    rmagick

It then deprecated the RMagick require.

If RMagick4J were to add a top-level require named rmagic, this would help packages (such as gruff) which can be used with either rmagic or RMagick4J.

This issue arose from https://github.com/topfunky/gruff/pull/127

**Comment by Serabe** [comment]
Where can I find this version? Currently I work on MacOS X and the problem I'm facing for this change is that I cannot keep both `RMagick.rb` and `rmagick.rb` as files for requiring.

**Comment by wconrad** [comment]
That was fast, and surprised me: I thought this was a "mostly dead" project.   So thanks!

> Where can I find this version?

I don't understand what you mean.  I didn't make a pull request, if that's what you were asking.

**Comment by Serabe** [comment]
This is mostly dead because I don't have time to implement things properly (and I'm really sad about this, believe me). But quick fixes are worth it. But the way, if you know of someone that wants to take over, let me know.

The problem is that I couldn't find the current repo of rmagick. Saw it in one of the issues finally.

**Comment by wconrad** [comment]
Sorry about that--I should have linked to it.  That was lazy on my part.  Thanks again for the fix.
